### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by molinto** [ndbroadbent/icloud_photos_downloader#11]
sharry:icloud_photos_downloader$ ./download_photos.py /home/sharry/Pictures/icloud/ --username=sharry@email.com --size=original --recent 200
iCloud password: PASSWORDHERE
```

Signing in...
Updating photos...
Traceback (most recent call last):
  File "./download_photos.py", line 231, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 55, in download
    updatePhotos(icloud)
  File "./download_photos.py", line 155, in updatePhotos
    icloud.photos.update()
AttributeError: 'PhotosService' object has no attribute 'update'

```

**Comment by ndbroadbent** [comment]
Hello, this looks like you are not using the correct version of `pyicloud`. This project depends on a branch, where the `update` method was added.

Please run `pip install -r requirements.txt`, or install it manually by running:

```
git+https://github.com/torarnv/pyicloud.git@photos-update#egg=pyicloud
```

**Comment by molinto** [comment]
Thank you, I'll give it a go :)
