### ISSUE TITLE
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

### ISSUE THREAD

**Issue by henk-hypershop** [ndbroadbent/icloud_photos_downloader#13]
When running, i get the following error:
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

Six has already been updated to latest version. Complete error output:

Traceback (most recent call last):
  File "./download_photos.py", line 10, in <module>
    import pyicloud
  File "/Library/Python/2.7/site-packages/pyicloud/__init__.py", line 2, in <module>
    from pyicloud.base import PyiCloudService
  File "/Library/Python/2.7/site-packages/pyicloud/base.py", line 18, in <module>
    from pyicloud.services import (
  File "/Library/Python/2.7/site-packages/pyicloud/services/__init__.py", line 7, in <module>
    from pyicloud.services.account import AccountService
  File "/Library/Python/2.7/site-packages/pyicloud/services/account.py", line 31, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

**Comment by ndbroadbent** [comment]
Sorry, I haven't seen that one before. But I googled for `python_2_unicode_compatible error`, and it seems to be quite common. I think it might be a problem with the python installation on your local machine.

Maybe your version of six is actually too high, and you should try downgrading to a lower version?

**Comment by ndbroadbent** [comment]
I am using version `1.4.1`

**Comment by henk-hypershop** [comment]
Managed to connect, but now i get the following error:

Traceback (most recent call last):
  File "./download_photos.py", line 231, in <module>
    download()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 55, in download
    updatePhotos(icloud)
  File "./download_photos.py", line 155, in updatePhotos
    icloud.photos.update()
  File "/Library/Python/2.7/site-packages/pyicloud/base.py", line 306, in photos
    self.params
  File "/Library/Python/2.7/site-packages/pyicloud/services/photos.py", line 35, in __init__
    params=self.params
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))

**Comment by tdubuffet** [comment]
`pip install --upgrade six`

It worked for me.

**Comment by ndbroadbent** [comment]
Thanks @tdubuffet. @henk-hypershop let is know if that fixes it for you.
