### ISSUE TITLE
Can't run pytest - syntax error?

### ISSUE THREAD

**Issue by menkej** [ndbroadbent/icloud_photos_downloader#135]
I tried to run the tests locally after installing the dependencies (on macOS). Unfortunately I run into issues, not related to the tests itself but to the framework. I don't know that framework. Any Ideas for troubleshooting?

$ pytest
Traceback (most recent call last):
  File "/usr/local/bin/pytest", line 7, in <module>
    from pytest import main
  File "/Library/Python/2.7/site-packages/pytest.py", line 10, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/Library/Python/2.7/site-packages/_pytest/fixtures.py", line 8, in <module>
    from more_itertools import flatten
  File "/Library/Python/2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from more_itertools.more import *  # noqa
  File "/Library/Python/2.7/site-packages/more_itertools/more.py", line 333
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax

It seems like some incompatibilities between python 2.7 and the latest versions of more_itertools. Found more info here: https://stackoverflow.com/questions/54648246/invalid-syntax-in-more-itertools-when-running-pytest

I'm not the python expert yet, so maybe someone can help. After digging I managed to run the tests with python3 so I can continue my work on #134 using python3 but I'd love to learn how to fix the toolchain in python 2.7

**Comment by ndbroadbent** [comment]
Hi @menkej, were you still struggling with this? You can see how I run the tests in [./scripts/test](https://github.com/ndbroadbent/icloud_photos_downloader/blob/master/scripts/test). It runs the tests for both Python 2 like this:

```
python2.7 -m pytest --cov=icloudpd
```

Another useful thing is that you can use the `-k` flag to just run a single test. I've been running:

```
python2.7 -m pytest -k test_listing_albums
```

**Comment by menkej** [comment]
Hi!
This is what I receive on a Mac:

$ python2.7 -m pytest --cov=icloudpd
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/pytest.py", line 10, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/Library/Python/2.7/site-packages/_pytest/fixtures.py", line 8, in <module>
    from more_itertools import flatten
  File "/Library/Python/2.7/site-packages/more_itertools/__init__.py", line 1, in <module>
    from more_itertools.more import *  # noqa
  File "/Library/Python/2.7/site-packages/more_itertools/more.py", line 329
    def _collate(*iterables, key=lambda a: a, reverse=False):
                               ^
SyntaxError: invalid syntax

I guess something is wrong with more_itertools… Ideas?

Cheers, Jörg
