### ISSUE TITLE
Installing requirements does not work

### ISSUE THREAD

**Issue by Yopplay** [ndbroadbent/icloud_photos_downloader#15]
Hi,
I am facing an issue with the requirements installation after having launched this command:`sudo pip install -r requirements.txt`, see out put below.

I do not know exactly what to do :-((.
I am running El Capitan.

I would like to thank you in advance for your help,

Yop.

`Requirement already satisfied: docopt in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: schema in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: click in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: python-dateutil in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from -r requirements.txt (line 4))
Requirement already satisfied: requests in /Library/Python/2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: tqdm>=4.5.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 6))
Collecting pyicloud from git+https://github.com/torarnv/pyicloud.git@photos-update#egg=pyicloud (from -r requirements.txt (line 7))
  Cloning https://github.com/torarnv/pyicloud.git (to photos-update) to /private/tmp/pip-build-Q820bR/pyicloud
Requirement already satisfied: keyring<9.0,>=8.0 in /Library/Python/2.7/site-packages (from pyicloud->-r requirements.txt (line 7))
Requirement already satisfied: keyrings.alt<2.0,>=1.0 in /Library/Python/2.7/site-packages (from pyicloud->-r requirements.txt (line 7))
Collecting six>=1.9.0 (from pyicloud->-r requirements.txt (line 7))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting tzlocal (from pyicloud->-r requirements.txt (line 7))
  Using cached tzlocal-1.4.tar.gz
Collecting certifi (from pyicloud->-r requirements.txt (line 7))
  Using cached certifi-2017.4.17-py2.py3-none-any.whl
Collecting bitstring (from pyicloud->-r requirements.txt (line 7))
  Using cached bitstring-3.1.5.zip
Collecting future (from pyicloud->-r requirements.txt (line 7))
  Using cached future-0.16.0.tar.gz
Requirement already satisfied: pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from tzlocal->pyicloud->-r requirements.txt (line 7))
Installing collected packages: six, tzlocal, certifi, bitstring, future, pyicloud
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-5vu5B1-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
`

**Comment by Yopplay** [comment]
I have solved my issue:
1. Install Homebrew
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
2. Install python
`Brew install python`
3. Install icloud_photo_downloader requirements
`sudo pip install -r requirements.txt`

It worked like a charm,
I'll try to download my pictures now ;-)

Thanks,
Kr,
yop
