### ISSUE TITLE
albumNameEnc error?

### ISSUE THREAD

**Issue by MrBenFTW** [ndbroadbent/icloud_photos_downloader#150]
Hello, I just did a fresh install of windows 10, I also tried this on centos. Both give the same error bellow: 

```
Traceback (most recent call last):
  File "icloudpd.py", line 5, in <module>
    main()
  File "C:\Users\Provision\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Provision\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Provision\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Provision\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Provision\Desktop\icloud_photos_downloader-master\icloudpd\base.py", line 276, in main
    photos = icloud.photos.albums[album]
  File "C:\Users\Provision\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\pyicloud_ipd\services\photos.py", line 194, in albums
    folder['fields']['albumNameEnc']['value']).decode('utf-8')
KeyError: 'albumNameEnc'
```

**Comment by pensphreak** [comment]
I'm having the same issue.  Ubuntu 20.04

./icloudpd.py -d ~/iCloudPhotos --username=xxxxx --password=xxxxx
2020-06-24 09:19:04 DEBUG    Authenticating...
Traceback (most recent call last):
  File "./icloudpd.py", line 5, in <module>
    main()
  File "/home/pens/.local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pens/.local/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pens/.local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pens/.local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pens/icloud_photos_downloader/icloudpd/base.py", line 276, in main
    photos = icloud.photos.albums[album]
  File "/home/pens/.local/lib/python3.8/site-packages/pyicloud_ipd/services/photos.py", line 194, in albums
    folder['fields']['albumNameEnc']['value']).decode('utf-8')
KeyError: 'albumNameEnc'

**Comment by pensphreak** [comment]
Turns out I had a weird ‘Untitled’/null album with no name and no photos in it.  I deleted that and everything seems to be running now.

**Comment by peiel** [comment]
I hava the same issues, win10.

```
Traceback (most recent call last):
  File "c:\users\administrator\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\administrator\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Anaconda3\Scripts\icloudpd.exe\__main__.py", line 9, in <module>
  File "c:\users\administrator\anaconda3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\administrator\anaconda3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\administrator\anaconda3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\administrator\anaconda3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\administrator\anaconda3\lib\site-packages\icloudpd\base.py", line 276, in main
    photos = icloud.photos.albums[album]
  File "c:\users\administrator\anaconda3\lib\site-packages\pyicloud_ipd\services\photos.py", line 194, in albums
    folder['fields']['albumNameEnc']['value']).decode('utf-8')
KeyError: 'albumNameEnc'
```

**Comment by cravussin** [comment]
same here, Catalina 10.15.4

`Traceback (most recent call last):
  File "/usr/local/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/icloudpd/base.py", line 276, in main
    photos = icloud.photos.albums[album]
  File "/usr/local/lib/python3.7/site-packages/pyicloud_ipd/services/photos.py", line 194, in albums
    folder['fields']['albumNameEnc']['value']).decode('utf-8')
`

**Comment by DeastinY** [comment]
While I don't know the origin of the error a fix is rather simple:
Open `"/usr/local/lib/python3.7/site-packages/pyicloud_ipd/services/photos.py", line 194` and change it from
`folder['fields']['albumNameEnc']['value']).decode('utf-8')` to
```
try:
    folder['fields']['albumNameEnc']['value']).decode('utf-8')
except KeyError:
    continue
```
this will skip the folder with the bad name.

**Comment by dariks** [comment]
@DeastinY I have tried your workaround, you seem to have an issue there.
Trying with your suggestion leads to an Syntax Error.
But i got it working:
```
try:                   
    folder_name = base64.b64decode(
        folder['fields']['albumNameEnc']['value']).decode('utf-8')
except KeyError:              
    continue
```

**Comment by maxexcloo** [comment]
@dariks thanks for the fix!

**Comment by genfersee** [comment]
@dariks thanks for the fix!

**Comment by madrubbishcat** [comment]
> While I don't know the origin of the error a fix is rather simple:
> Open `"/usr/local/lib/python3.7/site-packages/pyicloud_ipd/services/photos.py", line 194` and change it from
> `folder['fields']['albumNameEnc']['value']).decode('utf-8')` to
> 
> ```
> try:
>     folder['fields']['albumNameEnc']['value']).decode('utf-8')
> except KeyError:
>     continue
> ```
> 
> this will skip the folder with the bad name.

i tried to do this but it said permission denied...

**Comment by DeastinY** [comment]
try editing the file with admin rights

**Comment by maldeS** [comment]
> While I don't know the origin of the error a fix is rather simple:
> Open `"/usr/local/lib/python3.7/site-packages/pyicloud_ipd/services/photos.py", line 194` and change it from
> `folder['fields']['albumNameEnc']['value']).decode('utf-8')` to
> 
> ```
> try:
>     folder['fields']['albumNameEnc']['value']).decode('utf-8')
> except KeyError:
>     continue
> ```
> 
> this will skip the folder with the bad name.

Heyho,
the script checks for '----Root-Folder----'

`if folder['recordName'] == '----Root-Folder----' or \`

Within my data there was '----Project-Root-Folder----' as well. With e.g.:

`if folder['recordName'] == '----Project-Root-Folder----' or folder['recordName'] == '----Root-Folder----' or \`

it works for me.

Regards

**Comment by takelley1** [comment]
Are there any plans to create a pull request for this fix?

**Comment by ndbroadbent** [comment]
+1, unfortunately I don't have much time to work on this project, but I'm definitely happy to merge a PR and release a new version if all the tests are passing

**Comment by boredazfcuk** [comment]
I'd be interested in a fix for this, however, there isn't a "fix" as yet, is there?

It was my understanding that the workaround detailed here, only skips the files that present the problem, rather than provide a solution which enables their download.

**Comment by Appelg** [comment]
@maldeS solution worked for me too. Guess that's the most clean solution since the one where we ignore exceptions might give us other problems....

**Comment by Vlad1mir-D** [comment]
@ndbroadbent 
Can you please check this PR: https://github.com/ndbroadbent/pyicloud/pull/4 ?
Thanks!

**Comment by menkej** [comment]
> Can you please check this PR: [ndbroadbent/pyicloud#4](https://github.com/ndbroadbent/pyicloud/pull/4) ?
Works for me.

**Comment by ndbroadbent** [comment]
Thanks @Vlad1mir-D! I merged your PR and released a new version of icloudpd: 1.6.1. Please try that out and let me know if it fixes the issue

**Comment by Vlad1mir-D** [comment]
Thank you, @ndbroadbent!
Everything's fine.

**Comment by maldeS** [comment]
cool, works for me as well! thx.

**Comment by Monsterbacke007** [comment]
> Syn

With this I get 'continue not properly in loop'

**Comment by Monsterbacke007** [comment]
> 
> 
> @DeastinY I have tried your workaround, you seem to have an issue there.
> Trying with your suggestion leads to an Syntax Error.
> But i got it working:
> 
> ```
> try:                   
>     folder_name = base64.b64decode(
>         folder['fields']['albumNameEnc']['value']).decode('utf-8')
> except KeyError:              
>     continue
> ```

With this I get 'continue not properly in loop'
