### ISSUE TITLE
KeyError: 'albumNameEnc'

### ISSUE THREAD

**Issue by walkerwzy** [ndbroadbent/icloud_photos_downloader#157]
```
2020-07-23 10:48:46 DEBUG    Looking up all photos and videos...
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/icloudpd/base.py", line 253, in main
    photos = icloud.photos.all
  File "/usr/lib/python3.6/site-packages/pyicloud_ipd/services/photos.py", line 228, in all
    return self.albums['All Photos']
  File "/usr/lib/python3.6/site-packages/pyicloud_ipd/services/photos.py", line 194, in albums
    folder['fields']['albumNameEnc']['value']).decode('utf-8')
KeyError: 'albumNameEnc'
```

and my script is just like the `md` file:
```
$ docker run -it --rm --name icloud -v $(pwd)/Photos:/data ndbroadbent/icloudpd:latest \
    icloudpd /data \
    --username testuser@example.com \
    --password pass1234 \
    --size original \
    --recent 500 \
    --auto-delete
```

It's always successful all the time except today ( I use this script on or two month a time)
I've got nothing changed, and I double checked my album name, nothing wired character exists, except Chinese character, is this the reason? but they're here from a while and successfully downloaded many times.

**Comment by simon1573** [comment]
I'm getting the same error, with no Chinese character

**Comment by menkej** [comment]
This should be fixed with #150 . Please recheck @simon1573 and @walkerwzy . Thanks!
