### ISSUE TITLE
“Downloading the first original photo or video” then stops

### ISSUE THREAD

**Issue by woopiepoopie** [ndbroadbent/icloud_photos_downloader#167]
```
15macbookpro@15Macbookpro Pictures % icloudpd --directory /Volumes/Media/Pictures --username rpandula@uh.edu --password ******                                         
2020-10-07 14:06:12 DEBUG    Authenticating...
2020-10-07 14:06:19 DEBUG    Looking up all photos and videos from album All Photos...
2020-10-07 14:06:20 INFO     Downloading the first original photo or video to /Volumes/Media/Pictures/ ...
100%|#################################################################################| 1/1 [00:00<00:00,  1.62it/s]
2020-10-07 14:06:21 INFO     All photos have been downloaded!

```

I have about 40,000 photos+videos since 2010 on my iCloud Photo Library. Not sure why its stopping after downloading one random picture from 2019. Probably a simple config I’m missing, but i can’t seem to figure it out. 

I even tried telling it just download the most recent 40k pics

```
15macbookpro@15Macbookpro Pictures % icloudpd --directory /Volumes/Media/Pictures --username rpandula@uh.edu --password **** --set-exif-datetime --recent 40000 
2020-10-07 13:57:41 DEBUG    Authenticating...
2020-10-07 13:57:46 DEBUG    Looking up all photos and videos from album All Photos...
2020-10-07 13:57:46 INFO     Downloading 40000 original photos and videos to /Volumes/Media/Pictures/ ...
  0%|                                                                           | 1/40000 [00:00<3:30:16,  3.17it/s]
2020-10-07 13:57:47 INFO     All photos have been downloaded!

```

And I got the same issue. Any help would be much appreciated it

**Comment by AndreyNikiforov** [comment]
@woopiepoopie what version of icloudpd are you using? `icloudpd --version` should give you the answer

**Comment by woopiepoopie** [comment]
@AndreyNikiforov , thank you for the response! 

```
15macbookpro@15Macbookpro Pictures % icloudpd --version
icloudpd, version 1.6.1
```

Let me know if I can provide any other details

**Comment by woopiepoopie** [comment]
Update: Tried on my windows box as well (last one was macOS) 

Got the following error:
```

2020-10-09 11:47:11 DEBUG    Authenticating...
Traceback (most recent call last):
  File "c:\users\pcserver\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\pcserver\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\PCserver\AppData\Local\Programs\Python\Python39\Scripts\icloudpd.exe\__main__.py", line 7, in <module>
  File "c:\users\pcserver\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\pcserver\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\pcserver\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\pcserver\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\pcserver\appdata\local\programs\python\python39\lib\site-packages\icloudpd\base.py", line 292, in main
    directory = os.path.normpath(directory)
  File "c:\users\pcserver\appdata\local\programs\python\python39\lib\ntpath.py", line 452, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by AndreyNikiforov** [comment]
That helps a lot! I was able to reproduce the problem on python 3.9, while 3.8 works fine. Also, with `--no-progress-bar` option icloudpd works in both python versions. I suggest using `--no-progress-bar` until the issues is debugged and fixed. Please report if suggested workaround worked for you.
