### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Yopplay** [ndbroadbent/icloud_photos_downloader#17]
Hi,

Another issue: `IndexError: list index out of range` when launching my command to download all pictures and videos (see below).

Thanks for your help,

yop

`Traceback (most recent call last):
  File "./download_photos.py", line 231, in <module>
    download()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 54, in download
    icloud = authenticate(username, password)
  File "./download_photos.py", line 139, in authenticate
    device = devices[device]
IndexError: list index out of range`

**Comment by jspraul** [comment]
The only 2nd factor option I have is an iPhone 5S still back on iOS 10.2.

The first time, I got a UI prompt on the phone, with an option to 'approve' showing a location on a map, followed by a pop-up displaying a number to use for verification. However, I also received a text message with a different number. I input the number shown via the UI and was rejected. (```Failed to verify verification code```).

The second time, I got the UI prompts again, without a text message. I input the number shown via the UI and received the error mentioned above. So I decided to spam with this comment here!

```Traceback (most recent call last):
  File "./download_photos.py", line 231, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 54, in download
    icloud = authenticate(username, password)
  File "./download_photos.py", line 139, in authenticate
    device = devices[device]
```

After a brief wait, the third time, I got the UI prompts again and also a text message. This time I input the number in the text message and was able to proceed further.  I then hit an error similar to that which is expected the first time (specifically: connection timeout, details below), so I will try again in a few minutes.

```Updating photos...
Traceback (most recent call last):
  File "./download_photos.py", line 231, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 55, in download
    updatePhotos(icloud)
  File "./download_photos.py", line 155, in updatePhotos
    icloud.photos.update()
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 306, in photos
    self.params
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 35, in __init__
    params=self.params
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 473, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
```

**Comment by ndbroadbent** [comment]
Hello, sorry this is happening! I'm not sure if this is still happening, but we've made lots of changes to the script recently, so it might be fixed now.

This project is just a small wrapper around the [pyicloud](https://github.com/picklepete/pyicloud) library, so it might also be a problem with the pyicloud library. In that case, it could better to post an issue over there.
