### ISSUE TITLE
Windows 10 + Python 2.7NO JSON object could be decoded.

### ISSUE THREAD

**Issue by itadder** [ndbroadbent/icloud_photos_downloader#22]
Any ideas on the bellow issue? Running windows 2.7.2 bulid of python.
Updating photos...
Traceback (most recent call last):
  File "download_photos.py", line 231, in <module>
    download()
  File "c:\Python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\Python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\Python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "download_photos.py", line 55, in download
    updatePhotos(icloud)
  File "download_photos.py", line 155, in updatePhotos
    icloud.photos.update()
  File "c:\Python27\lib\site-packages\pyicloud\base.py", line 306, in photos
    self.params
  File "c:\Python27\lib\site-packages\pyicloud\services\photos.py", line 37, in __init__
    response = request.json()
  File "c:\Python27\lib\site-packages\requests\models.py", line 878, in json
    self.content.decode(encoding), **kwargs
  File "c:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "c:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by ryarca** [comment]
I have the same problem in Linux Ubuntu 16.04

**Comment by kvakulo** [comment]
Same issue on macOS Sierra. It was working just a few days ago, so maybe a change to iCloud?

**Comment by itadder** [comment]
Ahh so I have not been blacklisted.

**Comment by itadder** [comment]
It works for me in Ubuntu, but on windows 10, I still am getting 'File "C:\Python27\lib\json\decoder.py", line 382, in  raise ValueError("No JSON object could be decoded")"

**Comment by ndbroadbent** [comment]
Hi, sorry you're running into this issue. Looking at the traceback, the issue appears to originate in [pyicloud](https://github.com/picklepete/pyicloud), so it might better to open an issue over there.
