### ISSUE TITLE
Getting some error: Invalid global session

### ISSUE THREAD

**Issue by BuSHari** [ndbroadbent/icloud_photos_downloader#29]
Hello,

I'm getting an error 'Invalid global session' every time the downloader is reaching 100-200 photos.
I'm running it on my Synology Nas.

here is the 'Invalid global session' error
```
Downloading /volume1/Photo/iPhone-Backup/Idan-test/2017/07/24/IMG_7747-original.JPG:   4%| | 300/7346 [1:27:59<60:36:5        3, 30.97s/it]Traceback (most recent call last):
  File "/volume1/homes/BuSHari/iCloudDownloader/icloud_photos_downloader/download_photos.py", line 231, in <module>
    download()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/volume1/homes/BuSHari/iCloudDownloader/icloud_photos_downloader/download_photos.py", line 87, in download
    for photo in progress_bar:
  File "/usr/lib/python2.7/site-packages/tqdm/_tqdm.py", line 872, in __iter__
    for obj in iterable:
  File "/usr/lib/python2.7/site-packages/pyicloud/services/photos.py", line 281, in photos
    headers={'Content-type': 'text/plain'}
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/pyicloud/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python2.7/site-packages/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session
```

**Comment by ndbroadbent** [comment]
Hello, sorry this is happening! This project is just a small wrapper around the [pyicloud](https://github.com/picklepete/pyicloud) library, so it might be better to post an issue over there.
