### ISSUE TITLE
Error: Gone (410)

### ISSUE THREAD

**Issue by BuSHari** [ndbroadbent/icloud_photos_downloader#30]
Hello,

I'm getting some errors, and this is one of them: Gone (410).
I'm running it on my Synology Nas.

```
Downloading /volume1/Photo/iPhone-Backup/Idan-test/2017/07/15/IMG_7637-original.MOV:   5%| | 361/7349 [1:03:06<305:51:57s/it]Traceback (most recent call last):
  File "/volume1/homes/BuSHari/iCloudDownloader/icloud_photos_downloader/download_photos.py", line 231, in <module>
    download()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/volume1/homes/BuSHari/iCloudDownloader/icloud_photos_downloader/download_photos.py", line 112, in download
    download_photo(photo, download_path, size, force_size, download_dir, progress_bar)
  File "/volume1/homes/BuSHari/iCloudDownloader/icloud_photos_downloader/download_photos.py", line 206, in download_ph
    download_url = photo.download(size)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/pyicloud/services/photos.py", line 501, in downl
    **kwargs
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/pyicloud/base.py", line 74, in request
    self._raise_error(response.status_code, response.reason)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Gone (410)
```

**Comment by cincospenguinos** [comment]
I had this same issue. I'm running it on Mac OS X El Capitan with Python 3:

```
Traceback (most recent call last):
  File "download_photos.py", line 231, in <module>
    download()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "download_photos.py", line 112, in download
    download_photo(photo, download_path, size, force_size, download_dir, progress_bar)
  File "download_photos.py", line 206, in download_photo
    download_url = photo.download(size)
  File "/usr/local/lib/python3.6/site-packages/pyicloud/services/photos.py", line 501, in download
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pyicloud/base.py", line 74, in request
    self._raise_error(response.status_code, response.reason)
  File "/usr/local/lib/python3.6/site-packages/pyicloud/base.py", line 122, in _raise_error
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Gone (410)
```

**Comment by ndbroadbent** [comment]
Hi, sorry but I'm not sure what would be causing this. This project is just a small wrapper around the [pyicloud](https://github.com/picklepete/pyicloud) library, so it might be better to post over there.

**Comment by AlexanderWillner** [comment]
Same here and I'm not sure if it helps this project to close all issues unresolved by just pointing to https://github.com/picklepete/pyicloud. Created an issue there: https://github.com/picklepete/pyicloud/issues/151
