### ISSUE TITLE
auto-delete isn`t working

### ISSUE THREAD

**Issue by BuSHari** [ndbroadbent/icloud_photos_downloader#31]
Hi,

I'm getting that error when trying 'auto-delete' option

```
Signing in...
Looking up all photos...
Downloading 7338 original photos and videos to /volume1/Photo/iPhone-Backup/Idan/ ...
/volume1/Photo/iPhone-Backup/Idan/2010/04/07 already exists.: 100%|███████████████| 7338/7338 [04:04<00:00, 30.02it/s]
All photos have been downloaded!
Deleting any files found in 'Recently Deleted'...
Traceback (most recent call last):
  File "/volume1/@appstore/icloud_photo_station/app/download_photos.py", line 279, in <module>
    download()
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/volume1/@appstore/icloud_photo_station/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/volume1/@appstore/icloud_photo_station/app/download_photos.py", line 147, in download
    item = album.item(filename)
AttributeError: 'FileSystemAlbum' object has no attribute 'item'
```

**Comment by BuSHari** [comment]
That issue belong to other fork.
close
