### ISSUE TITLE
AttributeError: 'PyiCloudService' object has no attribute 'requires_2fa'

### ISSUE THREAD

**Issue by WhyNotHugo** [ndbroadbent/icloud_photos_downloader#39]
I'm getting a crash when trying to download photos:

```
$ ./download_photos.py my-photos --username hugo@barrera.io --password REDACTED
Traceback (most recent call last):
  File "./download_photos.py", line 252, in <module>
    download()
  File "/home/hugo/.local/share/virtualenvs/icloud/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/hugo/.local/share/virtualenvs/icloud/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/hugo/.local/share/virtualenvs/icloud/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hugo/.local/share/virtualenvs/icloud/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 91, in download
    smtp_username, smtp_password, smtp_host, smtp_port, smtp_no_tls, notification_email)
  File "/home/hugo/tmp/icloud_photos_downloader/authentication.py", line 10, in authenticate
    icloud = PyiCloudService(username, password)
  File "/home/hugo/.local/share/virtualenvs/icloud/lib/python3.6/site-packages/pyicloud/base.py", line 192, in __init__
    self.authenticate()
  File "/home/hugo/.local/share/virtualenvs/icloud/lib/python3.6/site-packages/pyicloud/base.py", line 211, in authenticate
    data=json.dumps(data)
  File "/home/hugo/.local/share/virtualenvs/icloud/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/hugo/.local/share/virtualenvs/icloud/lib/python3.6/site-packages/pyicloud/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/home/hugo/.local/share/virtualenvs/icloud/lib/python3.6/site-packages/pyicloud/base.py", line 105, in _raise_error
    if self.service.requires_2fa and \
AttributeError: 'PyiCloudService' object has no attribute 'requires_2fa'
```

My env:

```
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
docopt==0.6.2
future==0.16.0
idna==2.6
keyring==8.7
keyrings.alt==1.3
pyicloud==0.9.1
python-dateutil==2.6.1
pytz==2017.2
requests==2.18.4
schema==0.6.6
six==1.11.0
tqdm==4.17.1
tzlocal==1.4
urllib3==1.22
```

**Comment by ndbroadbent** [comment]
Ah sorry, this is a bug in the pyicloud library, but I've [included a fix for it in the script](https://github.com/ndbroadbent/icloud_photos_downloader/blob/master/authentication.py#L14-L17).

* Please make sure you're using the latest version of the script.
* Reinstall `pyicloud`:

```bash
pip uninstall pyicloud
pip install -r requirements.txt
```

Hope that helps!

**Comment by ndbroadbent** [comment]
Please reopen this issue if you are still experiencing problems.

**Comment by WhyNotHugo** [comment]
Thanks! I did have a few issues related to login, but I'll follow up upstream, since they're strictly `pyicloud`-related.
