### ISSUE TITLE
Problem with Unicode characters in destination path

### ISSUE THREAD

**Issue by YibaiMeng** [ndbroadbent/icloud_photos_downloader#40]
When I invoke the command with non-ascii characters in the destination path, there seem to be problems. For example, 
`mengyibai@my_computer:~/软件/icloud_photos_downloader$ ./download_photos.py ~/ 图片/iCloud_Photos` 
In this case, the following error would occur:

```python
Traceback (most recent call last):
  File "./download_photos.py", line 252, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 144, in download
    download_path = local_download_path(photo, size, download_dir)
  File "./download_photos.py", line 211, in local_download_path
    download_path = os.path.join(download_dir, filename)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 16: ordinal not in range(128)
```
and the program would terminate. However, if the destination path is changed to pure ascii, the program would run smoothly. The non-ascii characters in the path of the script appear to have no ill effects.

**Comment by ndbroadbent** [comment]
Hi, thanks for reporting this issue! It was working fine on Python 3.6, but this crash was happening on Python 2.7.

I've pushed a fix for the directory encodings on Python 2.7. Please update to the latest version of this script and try again. Thanks!
