### ISSUE TITLE
KeyError: u'resJPEGMedRes'

### ISSUE THREAD

**Issue by kristianunger** [ndbroadbent/icloud_photos_downloader#45]
Hi there,

I was using the following command:

~/icloud_photos_downloader/./download_photos.py ./ --username=user@email.com --size=original --download-videos

and received the following error lines after 93% of all files downloaded:

Traceback (most recent call last):
  File "/Users/unger/icloud_photos_downloader/./download_photos.py", line 255, in <module>
    download()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/unger/icloud_photos_downloader/./download_photos.py", line 158, in download
    download_photo(photo, download_path, size, force_size, download_dir, progress_bar)
  File "/Users/unger/icloud_photos_downloader/./download_photos.py", line 222, in download_photo
    if size not in photo.versions and not force_size and size != 'original':
  File "/Library/Python/2.7/site-packages/pyicloud/services/photos.py", line 487, in versions
    'size': f['%sRes' % prefix]['value']['size'],
KeyError: u'resJPEGMedRes'

Does anybody have suggestions how to solve this?

Many thanks,

Kristian

**Comment by cleygraf** [comment]
I have been hit by the same issue. Working through the traceback this seems to be an issue of pyicloud, which is used by this script. Checking pyicloud's github repository, I found, that there is already a fix: https://github.com/picklepete/pyicloud/issues/162 

But this patch hasn't made it to the main branch so far. Because I'm in a hurry, I've manually patched the file. And it does the trick, no more errors!

**Comment by ndbroadbent** [comment]
@cleygraf Thanks for letting my know about the fix! I've forked `pyicloud` and included these commits, and [updated the requirements.txt](https://github.com/ndbroadbent/icloud_photos_downloader/commit/4b71a18f26d59b33beae77e1ca31d7976da39afb) to point to the fork

**Comment by ndbroadbent** [comment]
@kristianunger It should be fixed if you run:

```
cd icloud_photos_downloader
git pull
sudo pip install -r requirements.txt
```
