### ISSUE TITLE
Error message ImportError: No module named 'pyicloud'

### ISSUE THREAD

**Issue by remoteblue** [ndbroadbent/icloud_photos_downloader#53]
Environment: ubuntu 16 LTS.

Install the package successfully. Install the requirement twice. This is the system message in the second installation. 

```
(carnd-term1-gpu) cocadas@cocadas-ThinkPad-W540:~/icloud_photos_downloader$ sudo pip install -r requirements.txt
The directory '/home/cocadas/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/cocadas/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: docopt in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: schema in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: click in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: tqdm==4.5.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pyicloud from git+https://github.com/picklepete/pyicloud.git#egg=pyicloud in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 5))
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 5))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 5))
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 5))
Requirement already satisfied: keyring<9.0,>=8.0 in /usr/local/lib/python2.7/dist-packages (from pyicloud->-r requirements.txt (line 7))
Requirement already satisfied: keyrings.alt<2.0,>=1.0 in /usr/local/lib/python2.7/dist-packages (from pyicloud->-r requirements.txt (line 7))
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from pyicloud->-r requirements.txt (line 7))
Requirement already satisfied: tzlocal in /usr/local/lib/python2.7/dist-packages (from pyicloud->-r requirements.txt (line 7))
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from pyicloud->-r requirements.txt (line 7))
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from pyicloud->-r requirements.txt (line 7))
```

Error message
```
(carnd-term1-gpu) cocadas@cocadas-ThinkPad-W540:~/icloud_photos_downloader$ ./download_photos.py ./iphoto --username=xyzemail --password=mypassword --size=original --download-videos --notification-email honghaot@gmail.com
Traceback (most recent call last):
  File "./download_photos.py", line 13, in <module>
    from authentication import authenticate
  File "/home/cocadas/icloud_photos_downloader/authentication.py", line 3, in <module>
    from pyicloud import PyiCloudService
ImportError: No module named 'pyicloud'
(carnd-term1-gpu) cocadas@cocadas-ThinkPad-W540:~/icloud_photos_downloader$ 
```

**Comment by liwenjie0728** [comment]
i meet the same problem

**Comment by jondwan** [comment]
I am getting a similar error - running this on 'Ubuntu 14.04 LTS' and also have 'Python 2.7.6' 

```
Traceback (most recent call last):
  File "./download_photos.py", line 13, in <module>
    from authentication import authenticate
  File "/home/jon/plex/icloud_photos_downloader/authentication.py", line 3, in <module>
    from pyicloud import PyiCloudService
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/__init__.py", line 2, in <module>
    from pyicloud.base import PyiCloudService
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 19, in <module>
    from pyicloud.services import (
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/__init__.py", line 7, in <module>
    from pyicloud.services.account import AccountService
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/account.py", line 31, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

**Comment by evenwebb** [comment]
I have also been having the same problem. 

Same error, OS and Python as @jondwan

**Comment by ndbroadbent** [comment]
I've been able to solve some pip issues by running `sudo pip uninstall pyicloud`, and then running `sudo pip install -r requirements.txt`. 

Could you please run `/usr/bin/env python --version`, and make sure that returns the correct version of Python?

**Comment by jondwan** [comment]
My version of python is 2.7.6 - i tried the above with no luck

**Comment by ndbroadbent** [comment]
Hello, I've decided to copy my `pyicloud` fork into this project (under `./vendor/pyicloud-0.9.1.zip`), and I've updated the `requirements.txt` to point to this zip file. 

First, please uninstall any existing versions of `pyicloud`: `sudo pip uninstall pyicloud`. Then confirm it's not installed by running `pip list | grep pyicloud` (output should be empty.)

Then you can install the fixed version by running: `sudo pip install -r requirements.txt`. 

Finally, running `pip list | grep pyicloud` should show:

```
$ pip list | grep pyicloud
pyicloud                      0.9.1
```

There's a few different ways to install Python 2 or 3, and different versions of `pip`. So make sure you're using the right version of `pip`. (On my system, I have to run `pip3` for the Python 3 version.)

Closing this for now, but please let me know if anyone is still running into issues, and I'll try to help you figure it out!
