### ISSUE TITLE
AttributeError: 'PyiCloudService' object has no attribute 'requires_2sa'

### ISSUE THREAD

**Issue by 91koff** [ndbroadbent/icloud_photos_downloader#64]
Traceback (most recent call last):
  File "./download_photos.py", line 304, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 100, in download
    smtp_username, smtp_password, smtp_host, smtp_port, smtp_no_tls, notification_email)
  File "/home/yakov/applications/icloudbackup/icloud_photos_downloader/authentication.py", line 19, in authenticate
    if icloud.requires_2sa:
AttributeError: 'PyiCloudService' object has no attribute 'requires_2sa'

**Comment by 91koff** [comment]
Looks like a typo in authentication.py. If change icloud.requires_2sa to icloud.requires_2fa it starts working.

**Comment by ndbroadbent** [comment]
Hi @91koff, it was actually changed to `requires_2sa` in a recent version of pyicloud, so you are probably using an older version. Please try to uninstall the pyicloud library, and reinstall with `pip install -r requirements.txt` (it points to the latest version on GitHub)

**Comment by 91koff** [comment]
Reinstalled pip, installed all requirements – now a I got a new issue. This can be closed.
