### ISSUE TITLE
Max retries exceeded with url

### ISSUE THREAD

**Issue by 91koff** [ndbroadbent/icloud_photos_downloader#65]
Looking up all photos...
Traceback (most recent call last):
  File "./download_photos.py", line 304, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 109, in download
    photos = icloud.photos.all
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 306, in photos
    self.params
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 35, in __init__
    params=self.params
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 67, in request
    response = super(PyiCloudSession, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='p30-photosws.icloud.com', port=443): Max retries exceeded with url: /ph/startup?clientBuildNumber=14E45&dsid=296618839&clientId=25DAB932-3C89-11E8-B4ED-D8D385AF9A0A (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9d5aa0d750>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by ndbroadbent** [comment]
Hi there, I think this might also be related to using the wrong version of `pyicloud`. Please trying updating pyicloud. You can also run: `pip install git+https://github.com/ndbroadbent/pyicloud.git#egg=pyicloud`

**Comment by 91koff** [comment]
Reinstalled pip, installed all requirements – now a I got a new issue. This can be closed.
