### ISSUE TITLE
Year is Out of Range Bug

### ISSUE THREAD

**Issue by lapint** [ndbroadbent/icloud_photos_downloader#74]
I'm trying to import all my photos from icloud. When it gets to a certain point it fails with the error: 
```
/home/luke/Pictures/2016/09/24/IMG_3101-original.JPG already exists.:  55%|▌| 18392/33335 [09:22<08:43, 28.56it/s]Traceback (most recent call last):
  File "./download_photos.py", line 304, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 152, in download
    created_date = photo.created.astimezone(get_localzone())
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 451, in created
    return self.asset_date
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 457, in asset_date
    tz=pytz.utc)
ValueError: year is out of range
```

**Comment by lapint** [comment]
I opened an issue in [pyicloud](https://github.com/picklepete/pyicloud/issues/180) because it looked like it could be rooted there?

**Comment by evenwebb** [comment]
I had this issue. I created a smart album in Photos on Mac to display all
photos older than 1990 and deleted the ones that came up as they had
corrupted dates. The years were set to 0000. It was some filter app that I
had used years back.

Hope this helps :)

**Comment by lapint** [comment]
@evenwebb Fantastic idea! Thanks for the advice, I'll try this afternoon! I'm almost certain that will fix the issue.

**Comment by lapint** [comment]
That worked, thanks so much.

**Comment by ndbroadbent** [comment]
Thanks for reporting this issue! I've fixed this with a workaround - https://github.com/picklepete/pyicloud/pull/184

I've also decided to store a copy of the pyicloud library in this repo (under `./vendor/pyicloud-0.9.1.zip`), because some people were having problems installing my fork from github. The `requirements.txt` has also been updated to point to this vendored copy.
So I've just updated that with this bugfix, and you can start using the fix by running `git pull`, then `pip install -r requirements.txt`
