### ISSUE TITLE
Crashed after auth?

### ISSUE THREAD

**Issue by invious** [ndbroadbent/icloud_photos_downloader#78]
I did
```
./download_photos.py /Volumes/SAMSUNG\ USB/Photos \
    --username=MyEmail@gmail.com \
    --password=MyAwesomePassword \
    --size=original
```
```
Please choose an option: [0]: 1
Please enter two-factor authentication code: 883838
Great, you're all set up. The script can now be run without user interaction.
You can also set up email notifications for when the two-step authentication expires.
(Use --help to view information about SMTP options.)
Looking up all photos and videos...
Downloading 3345 original photos and videos to /Volumes/SAMSUNG USB/Photos/ ...
Downloading /Volumes/SAMSUNG USB/Photos/2014/12/29/IMG_0927-original.MOV-originaDownloading /Volumes/SAMSUNG USB/Photos/2015/01/23/IMG_9797-original.jpeg:   0%| | 2/3345 [00:04<2:36:54,  2.82s/it]            Traceback (most recent call last):
  File "./download_photos.py", line 323, in <module>
    download()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 177, in download
    download_dir, progress_bar, only_print_filenames)
  File "./download_photos.py", line 259, in download_photo
    if size not in photo.versions and not force_size and size != 'original':
  File "/Library/Python/2.7/site-packages/pyicloud/services/photos.py", line 490, in versions
    if self.item_type == "movie":
  File "/Library/Python/2.7/site-packages/pyicloud/services/photos.py", line 484, in item_type
    self._master_record['fields']['itemType']['value']])
KeyError: u'public.png'
```

**Comment by ndbroadbent** [comment]
Hi @invious, sorry about that! I've just fixed the crash in my fork of the `pyicloud` library, so please run `git pull`, then `sudo pip install -r requirements.txt` to install the fixed version.

@bexelbie Hey, it looks like there's a few missing cases in #68. I've added 'public.png' to my fork, but I'm also going to check for the key in `self.ITEM_TYPES`, fall back to the filename extension, and then default to `movie`:

```
    @property
    def item_type(self):
        item_type = self._master_record['fields']['itemType']['value']
        if item_type in self.ITEM_TYPES:
            return self.ITEM_TYPES[item_type]
        if self.filename.lower().endswith(('.heic', '.png', '.jpg', '.jpeg')):
            return 'image'
        return 'movie'
```

If that looks good to you, you might want to update your `pyicloud` PR with that code: https://github.com/ndbroadbent/pyicloud/commit/b65053d7691f2dc435e5a79842fe0c73fc2f249f

**Comment by invious** [comment]
I pulled and reran pip install and I'm getting the same error message :/

```
  File "/Library/Python/2.7/site-packages/pyicloud/services/photos.py", line 490, in versions
    if self.item_type == "movie":
  File "/Library/Python/2.7/site-packages/pyicloud/services/photos.py", line 484, in item_type
    self._master_record['fields']['itemType']['value']])
KeyError: u'public.png'
```

**Comment by ndbroadbent** [comment]
Hmm, that's strange. I just checked the updated library in `vendor/pyicloud-0.9.1.zip` and it definitely contains the fix for `public.png`. Could you please try uninstalling `pyicloud` first with: `sudo pip uninstall pyicloud`? And then run `sudo pip install -r requirements.txt`. Then you should be using the updated version.

**Comment by ndbroadbent** [comment]
Ah great, I'm glad that fixed it! Good to know that the uninstall is required first, maybe that's because I didn't change the version. Anyway, glad you got it working, and let me know if you run into anything else!

**Comment by invious** [comment]
Quick question, I think my USB drive unmounted in the middle of the operation, how should I resume?

```
1445/3345 [1:11:55<8:40:23, 16.43s/it]
```

**Comment by ndbroadbent** [comment]
Hi there, it's safe to just run the script again, and it will skip any files that have already been downloaded.

**Comment by invious** [comment]
Whoa... I think I killed my USB drive. I thought it unmounted because it wasn't in Finder, and then I pulled it out... and now it can't be found by the OS. This is what happened when I pulled it out

```
Downloading /Volumes/SAMSUNG USB/Photos/2016/IMG_4861-original.MOV:  43%|4| 1446/3345 [1:12:41<13:20:46, 25.30s/it]IOError while writing file to /Volumes/SAMSUNG USB/Photos/2016/IMG_4860-original.MOV! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...
IOError while writing file to /Volumes/SAMSUNG USB/Photos/2016/IMG_4860-original.MOV! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...
IOError while writing file to /Volumes/SAMSUNG USB/Photos/2016/IMG_4860-original.MOV! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...
IOError while writing file to /Volumes/SAMSUNG USB/Photos/2016/IMG_4860-original.MOV! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...
IOError while writing file to /Volumes/SAMSUNG USB/Photos/2016/IMG_4860-original.MOV! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...
Could not download IMG_4860.MOV! Please try again later.
Downloading /Volumes/SAMSUNG USB/Photos/2016/IMG_4860-original.MOV:  43%|4| 1446Downloading /Volumes/SAMSUNG USB/Photos/2016/IMG_4860-original.MOV:  43%|4| 1447/3345 [1:13:04<13:00:02, 24.66s/it]Traceback (most recent call last):
  File "./download_photos.py", line 323, in <module>
    download()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 161, in download
    os.makedirs(download_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Volumes/SAMSUNG USB'

Aymons-MacBook-Air:icloud_photos_downloader aymon$ /Volumes/SAMSUNG USB/Photos/2016/
-bash: /Volumes/SAMSUNG: No such file or directory
Aymons-MacBook-Air:icloud_photos_downloader aymon$ cd /Volumes/SAMSUNG USB/Photos
```

I know this isn't your responsibility..

**Comment by ndbroadbent** [comment]
Oh damn! I hope it can be fixed. Are you sure you just didn't run out of space?

**Comment by invious** [comment]
Hey sorry, I have no idea what happened but found it again in preferences and healed it and it's all good
