### ISSUE TITLE
Bad Request on update Photos

### ISSUE THREAD

**Issue by tpohl** [ndbroadbent/icloud_photos_downloader#8]
Hi,
first: THANK YOU for creating this wonderful tool! It will finally give me peace of mind when my photos are finally backed up locally too!

Unfortunately I am experiencing an API Error. Here is my log:

`Signing in...
Updating photos...
Traceback (most recent call last):
  File "./download_photos.py", line 207, in <module>
    download()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./download_photos.py", line 51, in download
    icloud.photos.update()
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 95, in update
    data=data
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 500, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 101, in request
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Bad Request (400)`

Do you have any idea, what is going on here?

**Comment by ndbroadbent** [comment]
Hello, sorry about the error, I've also experienced this in the past. For some reason, I got 400 errors for the first few minutes, but if I retry 5 minutes later then everything works fine. I'm not sure what's causing this, but I think it's a problem with the `pyicloud` library. Please let me know if the error goes away when you retry in 5-10 minutes.

**Comment by tpohl** [comment]
Yes, that worked out! Thank you
