### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Cyrix126** [ndbroadbent/icloud_photos_downloader#93]
Hi,

When I run

`docker run -it --rm --name icloud -v $(pwd)/Photos:/data ndbroadbent/icloudpd:latest   icloudpd data --username=username --password=password --auto-delete`

I get:
```

2018-08-10 09:18:31 DEBUG    Authenticating...
2018-08-10 09:18:33 DEBUG    Looking up all photos and videos...
2018-08-10 09:18:34 INFO     Downloading 1749 original photos and videos to data/ ...
  0%|                                                                                                                                               | 0/1749 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/icloudpd/base.py", line 267, in main
    os.makedirs(download_dir)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: 'data/2018'

```

I'm running on KDE neon 5.13 as root.
Python 2.7.12
Docker version 17.03.2-ce, build f5ec1e2

Thanks for your time

**Comment by ndbroadbent** [comment]
Hi sorry for the delay! It looks like your container doesn't have permission to create directories in your `Photos` directory. Not too sure how to deal with that issue. I think a quick workaround would be to run the container with `--privileged`. That's usually not recommended in a production server environment, but in this case it's just a script running on your local machine, so I think it should be fine
